apiVersion: v1
kind: Service
metadata:
  name: udagram-api-users
  labels:
    app: udagram-api-users
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP    
  selector:
    app: udagram-api-users
