apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram_api_user
  name: udagram-api-user-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram_api_user
